/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author Pifko
 */
public class GameListView extends javax.swing.JPanel {

    /**
     * Creates new form GameList
     */
    public GameListView() {
        initComponents();
    }

    public JComboBox getGameLoadList_cbox() {
        return gameloadlist_cbox;
    }

    public JComboBox getGameJoinList_cbox() {
        return gamejoinlist_cbox;
    }

    public JButton getJoingame_btn() {
        return joingame_btn;
    }

    public JButton getLoadgame_btn() {
        return loadgame_btn;
    }

    public JButton getStartnewgame_btn() {
        return startnewgame_btn;
    }

    public JButton getRefreshlist_btn() {
        return refreshlist_btn;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameloadlist_cbox = new javax.swing.JComboBox();
        gamejoinlist_cbox = new javax.swing.JComboBox();
        startnewgame_btn = new javax.swing.JButton();
        loadgame_btn = new javax.swing.JButton();
        joingame_btn = new javax.swing.JButton();
        refreshlist_btn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 4));
        setPreferredSize(new java.awt.Dimension(786, 423));

        gameloadlist_cbox.setMinimumSize(new java.awt.Dimension(170, 22));
        gameloadlist_cbox.setPreferredSize(new java.awt.Dimension(220, 22));

        gamejoinlist_cbox.setMinimumSize(new java.awt.Dimension(33, 22));
        gamejoinlist_cbox.setPreferredSize(new java.awt.Dimension(33, 22));

        startnewgame_btn.setText("Start New Game");

        loadgame_btn.setText("Load Game");

        joingame_btn.setText("Join Game");
        joingame_btn.setActionCommand("");

        refreshlist_btn.setText("Refresh Game List");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(joingame_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loadgame_btn)
                .addGap(194, 194, 194))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(startnewgame_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshlist_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(gamejoinlist_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addComponent(gameloadlist_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gameloadlist_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gamejoinlist_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(loadgame_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(joingame_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startnewgame_btn)
                    .addComponent(refreshlist_btn))
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox gamejoinlist_cbox;
    private javax.swing.JComboBox gameloadlist_cbox;
    private javax.swing.JButton joingame_btn;
    private javax.swing.JButton loadgame_btn;
    private javax.swing.JButton refreshlist_btn;
    private javax.swing.JButton startnewgame_btn;
    // End of variables declaration//GEN-END:variables
}
